### ISSUE TITLE
Add custom realm support

### ISSUE THREAD

**Issue by Mitrofanov** [signalfx/enhanced-rds-monitoring#5]
If i use realm different from default (US0) - it looks like i can't send metrics to SFX.

I guess we need to add something like

```
signalfx.SignalFx(api_endpoint='https://api.{REALM}.signalfx.com',
        ingest_endpoint='https://ingest.{REALM}.signalfx.com',
        stream_endpoint='https://stream.{REALM}.signalfx.com')
```
Per https://github.com/signalfx/signalfx-python/blob/master/README.rst

**Comment by mmusik** [comment]
Hi @Mitrofanov I realize that this is probably irrelevant by now, but this is supported via an environment variable 'realm' (or the parameter 'Realm' in case you deploy from Serverless App Repo).
