### ISSUE TITLE
Tox unclear on how to handle 'groups' environment variable

### ISSUE THREAD

**Issue by makusu2** [signalfx/enhanced-rds-monitoring#8]
Running Tox, I get a lot of:
```
======================================================================
ERROR: test_standard_parsing (__main__.TestLambdaComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unittests.py", line 137, in test_standard_parsing
    desired_metrics_info = pull_metric_names(e(my_sql_dict['engine']))
  File "/code/enhanced-rds-monitoring/enhanced_rds/lambda_script.py", line 348, in pull_metric_names
    if os.environ['groups'] != 'All':
  File "/code/enhanced-rds-monitoring/.tox/py37/bin/../lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'groups'
```
It doesn't have a `groups` environment variable, which makes sense, since I'm not seeing it ever get set.  Setting it along with the `tox` command doesn't seem to do anything, which I assume has to do with how Tox runs its tests. 

Could it be clarified what I'm meant to do about that environment variable?

**Comment by makusu2** [comment]
Oops, by the way, I'm running it in Python3.7, as the default Tox configuration doesn't work at all (the requirements are missing a `boto3` import). I'm submitting a PR later to fix it.

**Comment by mmusik** [comment]
Should be ok now. Let me know if you still run into troubles in your setup.
